FROM python:3.12-slim

WORKDIR /app

RUN sed -i 's|http://deb.debian.org|https://deb.debian.org|g' /etc/apt/sources.list.d/debian.sources

RUN apt-get update \
    && apt-get install -y --no-install-recommends mosquitto \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.zededa.txt .
RUN pip install --no-cache-dir -r requirements.zededa.txt

COPY well_register.yaml .
COPY sensor_simulator.py .
COPY edge_processor.py .
COPY data_logger.py .
COPY dashboard.py .
COPY mosquitto/mosquitto.conf .
COPY start_all.sh .

RUN chmod +x start_all.sh

EXPOSE 8501 1883

CMD ["/app/start_all.sh"]
